name = "pyxem"
version = "0.11.0dev"
author = "Duncan Johnstone, Phillip Crout"
copyright = "Copyright 2017-2019, The pyXem Developers"
credits = ["Duncan Johnstone", "Phillip Crout", "Ben Martineau", "Simon Hogas"]
license = "GPLv3"
maintainer = "Duncan Johnstone, Phillip Crout"
email = "pyxem.team@gmail.com"
status = "Development"
