name = "pyxem"
version = "0.12.0"
author = "Duncan Johnstone, Phillip Crout, Magnus Nord"
copyright = "Copyright 2017-2020, The pyXem Developers"
credits = ["Duncan Johnstone", "Phillip Crout", "Magnus Nord", "Ben Martineau", "Simon Hogas"]
license = "GPLv3"
maintainer = "Duncan Johnstone, Phillip Crout, Magnus Nord"
email = "pyxem.team@gmail.com"
status = "Development"
