name: Docs

on: [push, pull_request]

jobs:
  build_doc:
    name: Docs (PR comments)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ubuntu packages
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
          sudo apt-get install build-essential
          sudo apt-get install latexmk
          sudo apt-get install texlive-fonts-recommended

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install pyxem
        shell: bash -l {0}
        run: |
          pip install .[all,doc]

      - name: Build Documentation
        shell: bash -l {0}
        run: |
          cd doc
          make html
        env:
          PYXEM_SKIP_SLOW_EXAMPLES: "1"  # Skip slow examples for faster CI builds

      - uses: actions/upload-artifact@v4
        with:
          path: ./doc/_build/html/
          name: doc_build

  check_links:
    # This build is to check external links
    name: Check external links
    runs-on: ubuntu-latest
    env:
      DOCS_PATH: ./doc/_build/html/
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install build docs
        shell: bash -l {0}
        run: |
          pip install .[doc]

      - name: Check links
        shell: bash -l {0}
        run: |
          cd doc
          make linkcheck